=== Documentation

The Yocto Project documentation is perfect as a long term reference, when we are aware of what we are looking for, and has a base knowledge about its tools. This set of documents, along with this book, are a powerful combination to have around during the journey, diving into the Yocto Project.

A collection of well-focused documentation is available in the Yocto Project and can be seen at the link:https://docs.yoctoproject.org[website] and the most commonly used ones are:

link:https://docs.yoctoproject.org/brief-yoctoprojectqs/index.html[Yocto Project Quick Build]::
It is likely to be the very first contact with the project's documentation as it presents the needed information to get started with the Yocto Project quickly and start building an image.

link:https://docs.yoctoproject.org/dev-manual/index.html[Yocto Project Development Tasks Manual]::
Provides an overview of common tasks for kernel and user-space development. Actually, it gathers together references to other sources where we can find the detailed information.

link:https://docs.yoctoproject.org/kernel-dev/index.html[Yocto Project Linux Kernel Development Manual]::
Describes the Yocto Project Linux Kernel framework, how to use and customize it.

link:https://docs.yoctoproject.org/bsp-guide/index.html[Yocto Project Board Support Package (BSP) Developer's Guide]::
Defines the general guidelines and standardization for BSP metadata, tools and concepts.

link:https://docs.yoctoproject.org/sdk-manual/index.html[Yocto Project Application Developer's Guide]::
Provides information to get us started with the application SDK.  Handy to develop user-level application and low-level development.

link:https://docs.yoctoproject.org/bitbake.html[BitBake Documentation]::
Provides usage and reference material, including the metadata syntax, for the BitBake tool.

link:https://docs.yoctoproject.org/ref-manual/index.html[Yocto Project Reference Manual]::
Provides a reference to the Yocto Project, including variables, classes and other metadata information which are of great value during day-by-day use of Yocto Project tools. Undoubtedly, the most commonly used manual.

link:https://docs.yoctoproject.org/profile-manual/index.html[Yocto Project Profiling and Tracing Manual]::
This document describes how to take advantage of the gathered profiling and tracing tools available in the Yocto Project.

There are several benefits of joining a community, some of those can be personal others professional. It is important that you find your own way to enjoy and contribute to the community that makes sense for you and is aligned to your goals. An advice, when joining a new community, is to follow the target mailing list in order to learn how that community behaves before actually starting to contribute and, at end of the day, become part of it.
